### ISSUE TITLE
[Training Scripts and Environment Setup to Reproduce Results]

### ISSUE THREAD

**Issue by hungdinhxuan** [cyjie429/RawBMamba#1]
The results you have shared are impressive, and I am very interested in reproducing them for my research purposes. However, I am currently facing some challenges in replicating the results as described in your paper. To help me and others in the community, could you please provide the following:
 1. Training Scripts: Detailed instructions on how to run these scripts, including any command-line arguments or configuration files required.
 2. Environment Setup: A list of all dependencies and their versions.
 
 Providing these details will greatly help in ensuring that the results can be accurately reproduced and will enhance the usability of your project for the community.

**Comment by cyjie429** [comment]
Thank you for your attention. I will reorganize the code immediately and upload our trained model parameters for the community to use.
