### ISSUE TITLE
The enquiry of the sampling rate of RawBMamba

### ISSUE THREAD

**Issue by swagshaw** [cyjie429/RawBMamba#2]
https://github.com/cyjie429/RawBMamba/blob/046431062f74c67d335226c70bfd318313fb9688/feature_extract.py#L130

Thank you for this novel work, it gives me much inspiration. However, as you mentioned in paper:
![image](https://github.com/user-attachments/assets/b09d3a7b-f46d-48ed-a6c8-1053491e3eaa)

I would like to ask what is your sampling rate here. Is it 22050 as the default of librosa.load()? According to your paper description, the sampling rate should be 16000. Would you mind checking for me? I will be very appreciative.

**Comment by swagshaw** [comment]
@cyjie429

**Comment by cyjie429** [comment]
Thank you very much for your interest in our work. We apologize for any misunderstanding this may have caused. Just to clarify, the default for librosa.load() is 22050.
